export const LOGISIM = 'logisim';
export const VERILOG = 'verilog';
export const PYTHON_3 = 'Python 3';
export const PYQT5 = 'PyQt5';
export const RASPBERRY_PI = 'Raspberry Pi';
export const ARDUINO_UNO = 'Arduino Uno';
export const RUBY_ON_RAILS = 'Ruby on Rails'
export const AWS_EC2 = 'AWS EC2';
export const NEXT_JS = 'Next.js';
export const TYPESCRIPT = 'Typescript'
export const TAILWIND_CSS = "Tailwind CSS";
export const GITHUB_PAGES = 'GitHub Pages';
export const VERCEL = 'Vercel';
export const STYLED_COMPONENTS = 'styled-components';
export const CPP = 'C++';
export const WIN32_API = 'Win32 API'
